services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tansu_test
      POSTGRES_PASSWORD: tansu_test
      POSTGRES_DB: tansu_test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "tansu_test", "-d", "tansu_test" ]
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
