name: Publish Soroban versioning contract

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Unique release name"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-contract:
    name: Compile Stellar smart contract for production and create release
    permissions:
      contents: write # in order to create releases
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@4d0117fd348fb90cc36e2cd8c774f822802752af
    with:
      release_name: ${{ github.event.inputs.release_name }}
      release_description: "Tansu contract release"
      relative_path: '["contracts/versioning"]'
      package: 'versioning'
      make_target: 'build'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
#  attestation-contract:
#    needs: release-contract
#    runs-on: ubuntu-latest
#    steps:
#      - name: Generate artifact attestation for build
#        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c
#        with:
#          subject-path: "target/wasm32-unknown-unknown/release/versioning.wasm"
#
#      - name: Verify artifact attestation
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        shell: bash
#        run: |
#          for artifact in target/wasm32-unknown-unknown/release/*; do
#              echo "# ${artifact}"
#              gh attestation verify "${artifact}" --repo ${{ github.repository }}
#          done
