name: dApp upload to IPFS

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - "dapp/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ipds:
    name: Publish dApp on IPFS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    environment:
      name: dapp-ipfs
    defaults:
      run:
        working-directory: ./dapp

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install App dependencies
        run: bun install

      - name: Build app
        run: bun run build

      - name: Generate artifact attestation for dist
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a
        with:
          subject-path: "./dapp/dist/*"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: |
            ./dapp/dist/*

      # https://web3.storage/docs/how-to/ci/#github-action-add-to-web3
      - uses: web3-storage/add-to-web3@afd8cba20f920c998f6d3b38db0abe64242fe042
        id: w3up
        with:
          path_to_add: "./dapp/dist"
          proof: ${{ secrets.W3_PROOF }}
          secret_key: ${{ secrets.W3_PRINCIPAL }}

      - name: Job summary
        run: |
          echo "### Shipping to IPFS! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- CID: ${{ steps.w3up.outputs.cid }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- URL: ${{ steps.w3up.outputs.url }}" >> "$GITHUB_STEP_SUMMARY"
